//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentappDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelData
    {
        public HostelData()
        {
            this.StudentData = new HashSet<StudentData>();
        }
    
        public int ID { get; set; }
        public string HostelName { get; set; }
        public string Block { get; set; }
        public int RoomNumber { get; set; }
    
        public virtual ICollection<StudentData> StudentData { get; set; }
    }
}
